# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-18 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.IntegerField(default=0)),
                ('description', models.TextField(max_length=1000)),
                ('pic', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('SKU', models.CharField(max_length=32)),
                ('description', models.TextField(max_length=1000)),
                ('pic', models.CharField(max_length=500)),
            ],
        ),
    ]
