# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-20 06:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_products_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='stockable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='subcategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('pic', models.CharField(max_length=500)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.categories')),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='is_stockable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='products',
            name='price1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='products',
            name='price2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='products',
            name='price3',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.subcategories'),
        ),
        migrations.AddField(
            model_name='stockable',
            name='items',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.products'),
        ),
    ]
