# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-20 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20160920_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='description',
            field=models.TextField(default=None, max_length=1000),
        ),
        migrations.AlterField(
            model_name='categories',
            name='pic',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='products',
            name='SKU',
            field=models.CharField(default=None, max_length=32),
        ),
        migrations.AlterField(
            model_name='products',
            name='pic',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='subcategories',
            name='description',
            field=models.TextField(default=None, max_length=1000),
        ),
        migrations.AlterField(
            model_name='subcategories',
            name='pic',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
