# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-05 21:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Akun_l1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=1)),
                ('nama', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Akun_l2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=1)),
                ('nama', models.CharField(max_length=40)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Akun_l1')),
            ],
        ),
        migrations.CreateModel(
            name='Akun_l3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=2)),
                ('nama', models.CharField(max_length=40)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Akun_l2')),
            ],
        ),
    ]
