# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-05 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='akun_l1',
            name='id',
        ),
        migrations.RemoveField(
            model_name='akun_l2',
            name='id',
        ),
        migrations.RemoveField(
            model_name='akun_l3',
            name='id',
        ),
        migrations.AlterField(
            model_name='akun_l1',
            name='kode',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='akun_l2',
            name='kode',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='akun_l3',
            name='kode',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
