# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-07 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20160806_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='akun_l3',
            name='kode_lv',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
