# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-07 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20160807_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='akun_l2',
            name='kode_lv',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
