# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-08 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20160807_1908'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('details', models.CharField(max_length=100)),
                ('kode', models.CharField(max_length=100)),
                ('Jumlah', models.BigIntegerField()),
                ('Quantity', models.IntegerField()),
            ],
        ),
    ]
