# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-08 10:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='Jumlah',
            new_name='jumlah',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='Quantity',
            new_name='quantity',
        ),
    ]
