# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-08 14:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20160808_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bahan_baku',
            fields=[
                ('kode', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('harga_beli', models.BigIntegerField()),
                ('quantity', models.IntegerField()),
                ('nama', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Satuan_bb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='bahan_baku',
            name='satuan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Satuan_bb'),
        ),
    ]
