# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-11 15:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20160808_2138'),
    ]

    operations = [
        migrations.CreateModel(
            name='bb_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('used', models.IntegerField(default=0)),
                ('add', models.IntegerField(default=0)),
                ('last_price', models.BigIntegerField()),
                ('last_hpp', models.BigIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='bahan_baku',
            name='hpp',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bahan_baku',
            name='used',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bb_log',
            name='kode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Bahan_baku'),
        ),
    ]
