# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-11 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20160811_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bahan_baku',
            name='harga_beli',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bahan_baku',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bb_log',
            name='last_hpp',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bb_log',
            name='last_price',
            field=models.BigIntegerField(default=0),
        ),
    ]
