# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 04:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20160811_2217'),
    ]

    operations = [
        migrations.CreateModel(
            name='bb_stock',
            fields=[
                ('kode', models.AutoField(primary_key=True, serialize=False)),
                ('harga_beli', models.BigIntegerField(default=0)),
                ('hpp', models.BigIntegerField(default=0)),
                ('quantity', models.IntegerField(default=0)),
                ('used', models.IntegerField(default=0)),
                ('nama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Bahan_baku')),
                ('satuan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Satuan_bb')),
            ],
        ),
        migrations.AddField(
            model_name='bb_log',
            name='kode_stock',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
