# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 04:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20160818_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bb_log',
            name='kode_stock',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
