# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_bb_log_kode_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='bb_log',
            name='kode_stock',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
