# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 14:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_bb_log_kode_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bb_log',
            name='kode',
        ),
        migrations.DeleteModel(
            name='bb_log',
        ),
    ]
