# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 14:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20160818_2154'),
    ]

    operations = [
        migrations.CreateModel(
            name='bb_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_stock', models.CharField(max_length=100, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('used', models.IntegerField(default=0)),
                ('add', models.IntegerField(default=0)),
                ('last_price', models.BigIntegerField(default=0)),
                ('last_hpp', models.BigIntegerField(default=0)),
                ('kode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Bahan_baku')),
            ],
        ),
    ]
