# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_bb_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bb_log',
            name='kode_stock',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
