# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20160902_0138'),
    ]

    operations = [
        migrations.AddField(
            model_name='produk',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
