# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20160902_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produk',
            name='kode',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
