# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-02 12:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20160902_0240'),
    ]

    operations = [
        migrations.CreateModel(
            name='abc_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(choices=[(1, 'Januari'), (2, 'Februari'), (3, 'Maret'), (4, 'April'), (5, 'Mei'), (6, 'Juni'), (7, 'Juli'), (8, 'Agustus'), (9, 'September'), (10, 'Oktober'), (11, 'November'), (12, 'Desember')])),
                ('year', models.IntegerField()),
                ('bbl', models.BigIntegerField(default=0)),
                ('bbtl', models.BigIntegerField(default=0)),
                ('unit_produksi', models.IntegerField(default=0)),
                ('hpp_unit', models.BigIntegerField(default=0)),
                ('costdriver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cost_driver')),
                ('produk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Produk')),
            ],
        ),
    ]
